# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadProductiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('votante_asociado', models.IntegerField(default=0)),
                ('fecha_visita', models.DateField(default=datetime.date.today)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visita.ActividadProductiva')),
                ('partido', models.ManyToManyField(to='visita.Partido')),
            ],
        ),
    ]
