# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='oficialista',
            field=models.BooleanField(default=False),
        ),
    ]
