# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuo',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='padron.Departamento'),
            preserve_default=False,
        ),
    ]
