# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_individuo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(default=1),
        ),
    ]
