# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0003_departamento_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['codigo']},
        ),
        migrations.RenameField(
            model_name='seccional',
            old_name='numero',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='districto',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
