# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0003_auto_20170720_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='permiso',
            field=models.BooleanField(default=False, help_text='El Usuario podra revisar toda la estructura?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
