# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0004_auto_20170721_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
