# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0005_auto_20170721_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_id',
            field=models.BigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
