# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0007_candidato_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='level',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='persona',
            name='permiso',
            field=models.BooleanField(default=False, help_text='El Usuario podra revisar toda la estructura?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
