# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0008_auto_20170724_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='permiso',
        ),
    ]
