# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campana', '0010_candidato_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
