# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('apellido', models.CharField(blank=True, max_length=200)),
                ('nacimiento_fecha', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10)),
                ('nacimiento_lugar', models.CharField(blank=True, max_length=200)),
                ('profesion', models.CharField(max_length=200)),
                ('domicilio', models.CharField(max_length=500, null=True)),
                ('barrio_ciudad', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=5)),
                ('conyuge_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identificacion.Persona')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='identificacion.Nacionalidad')),
            ],
        ),
    ]
